/**
 * Appifex Configuration for Generated Apps
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated during code generation and contains
 * project/session metadata required for error tracking and debugging.
 *
 * Why hardcoded values:
 * Environment variables (EXPO_PUBLIC_*) are processed at build time by Metro,
 * but may not be available at runtime in all scenarios. This config file uses
 * template placeholders that are replaced during deployment with actual values
 * to ensure they're always accessible for error tracking.
 */

interface AppifexConfig {
  readonly projectId: string;
  readonly sentryDsn: string;
  readonly backendUrl: string;
}

/**
 * Creates and validates Appifex configuration.
 * Template placeholders ({{PLACEHOLDER}}) are replaced during deployment.
 */
function createAppifexConfig(): AppifexConfig {
  const config = {
    /** Links this app to an Appifex project */
    projectId: 'b7a5c16d-1d6b-4767-b200-20de6e4a6c01',
    /** Sentry DSN for centralized error monitoring */
    sentryDsn: 'https://9f6aa8afe9f2ed6597cc4e908a9f5986@o4510566327844864.ingest.us.sentry.io/4510566372737024',
    /** Appifex backend URL for telemetry */
    backendUrl: 'https://api.appifex.ai',
  };

  // Validation: warn if template placeholders weren't replaced
  // This helps catch deployment configuration issues
  if (config.projectId.indexOf('{{') !== -1) {
    console.warn(
      '⚠️ Appifex metadata contains template placeholders - deployment may be misconfigured.\n' +
      'Error tracking may not work correctly. Check deployment logs for env injection errors.'
    );
  }

  // Validation: warn if values are empty (shouldn't happen with proper deployment)
  if (!config.projectId) {
    console.warn(
      '⚠️ Appifex metadata is empty - error tracking may not work.\n' +
      'Errors will still be captured by Sentry but may not appear in the Appifex dashboard.'
    );
  }

  // Debug: Log config values on startup (masked for security)
  console.log('[Appifex Config] Loaded:', {
    projectId: config.projectId.length > 8 ? config.projectId.substring(0, 8) + '...' : config.projectId,
    hasDsn: !!config.sentryDsn && config.sentryDsn.length > 10,
    isTemplate: config.projectId.includes('{{'),
  });

  return config;
}

export const APPIFEX_CONFIG = createAppifexConfig();
